weekly_hours = 10
db_id = "061a26b964d041c397e0b323220c6e8c"
time_entries_query_url = "https://api.notion.com/v1/databases/061a26b964d041c397e0b323220c6e8c/query"
new_page_url = "https://api.notion.com/v1/pages"